### ISSUE TITLE
The question about use a full set of HTC VIVE

### ISSUE THREAD

**Issue by Yi-Meng** [Megasteakman/VRMocap#12]
I use the HTC vive HMD and vive controller, and character model form metahuman. When I done everything that I should do before run the game. controllers and trackers is useless.  I make sure livelinkXR is normal, because they can control other object like cube and camera. At last I want to know that can VRMocap is used on a full set of HTC VIVE.
ps: My English is not well because it is not my native language. If I’m not accurate enough that you don’t understand, please let me know.

**Comment by Yi-Meng** [comment]
And I have another question
vive controller can't be identify may be due to they isn't valve index controller that you used. but vive tracker can't be identify, too.  I can't understand that.

**Comment by Megasteakman** [comment]
Did you change the livelink xr names in the player pawn?  You can either change the default player pawn so every time you drag that in it has the right values or you can change the player pawn instance that you auto-possess in your level.  You can find out more about that process here:

https://github.com/Megasteakman/VRMocap/wiki#first-time-set-up

Vive trackers should still work because they are steamvr tracked devices, but you will have to redo the inputs in the engine settings to use that controller instead of the index.  I hope that helps!

**Comment by Yi-Meng** [comment]
Thank you for your help, I have solved the previous problem. At the same time, I also modified VRMocap_Player_Pawn_BP to adapt to the vive controller. I have submitted the changes as a branch.
In addition, I have another question. I want to use the daz model instead of the CC3 model. Where do I need to modify to achieve this goal? After I finish, I will submit the results again to make VRMocap more and more useful. I hope you can give me some help.
Finally, thank you again.

**Comment by Megasteakman** [comment]
Sorry it's taken me so long to get back to you: I've been on vacation for the last week!

Hmm, for Daz I would try out the 'Unknown' actor type.  The control rig isn't as specific as the CC3 character type however, so it might be worth revising one of those to work with the new skeleton, and adding that one to the animation blueprint instead of the unknown control rig.  

I think the VRMocap system needs a refactor where all the characters use an interface vs the casting from the player pawn I originally did.  It's a little hard to add new actor types because the system because of that, but I think the easiest way to add a new skeleton is basing it off of the 'Unknown' animation blueprint and 'Unknown' logic in the player pawn.  I'm not sure when I can add this, as I am pretty slammed at work, and I don't have any free time for the foreseeable month.
