### ISSUE TITLE
VRTrackerOffsetVisualizer unable to find player pawn

### ISSUE THREAD

**Issue by zhangfa** [Megasteakman/VRMocap#16]
First, Thank you very much for sharing the project.
I have some strange problems, like "VRTrackerOffsetVisualizer unable to find player pawn". 
I followed your setup video steps by steps. And when I Play, this log will be printed on screen.
I find in the blueprint, "GetPlayerSpawn" will always return the "SpectatorPawn" node.
Can you help me?
Thanks all the time.

**Comment by zhangfa** [comment]
Sorry, I play the wrong mode. I used the simulate.

**Comment by mdekys** [comment]
Hello, I also have this problem: when having "Debug Strings Hud On" I got
**VRTrackerOffsetVisualizer unable to find player pawn**
error displayed briefly after entering play mode 
even if I'm runing play mode in current viewport (meaning not in simulation mode as zhangfa mentioned above)

![Screenshot_6](https://user-images.githubusercontent.com/8372379/146960635-06651f2a-9b92-4cd9-8773-a3f30d99eff9.jpg)


because of this, I cannot see any trackers moving in realtime (all of them is stuck in VRMocap_PlayerPawn_BP's root)

My player Pawn controller ID index is 0
![Screenshot_6](https://user-images.githubusercontent.com/8372379/146960635-06651f2a-9b92-4cd9-8773-a3f30d99eff9.jpg)

as well as Player Index set to 0 on my MocapActorComponent

![Screenshot_8](https://user-images.githubusercontent.com/8372379/146961424-e1187ea6-c6cf-4468-94fd-a0e52ae457e5.jpg)


Could you please help me? I really like your mocap solution and I believe this is just some minor thing that I cannot figure out. Thanks!

**Comment by Megasteakman** [comment]
The VRTrackerOffsetVisualizer was a widget that I made for alignment that got deprecated, and shouldn't effect the tracking.  Everything looks correct, but if when you enter playmode the player pawn rings don't snap to the actor, make sure you are set to auto possess the pawn or use the provided game mode to spawn in a player pawn that you are possessing.

I believe the trackers should always be moving, so make sure you have the live link xr plugin installed and that you are using the device IDs of your trackers.  The defaults in the system are min, so that could be another issue.  Maybe try running through this 'pre-flight' quickstart really fast on the wiki: https://github.com/Megasteakman/VRMocap/wiki#first-time-set-up

I hope this helps, but let me know if you have any other issues.

**Comment by mdekys** [comment]
thank you so much for reply! setting "Auto Posses Player" to "Player 0" instead of default Disabled on VRMocap_PlayerPawn_BP helped and now I can see the movement of trackers inside play mode. 

However. the red ring stays on the same position and won't move trackers as seen on your videos  (maybe that's the VRTrackerOffsetVisualizer which got disabled by setting Auto Posses Player?
![Screenshot_9](https://user-images.githubusercontent.com/8372379/147228652-13544bfb-d597-4d50-b5ee-a31512e2c9f7.jpg)
I believe because of this, it makes me unable to align with player correctly resulting in not-accurate player animations

I'm running  latest version from git (rev.56707ce) on UE 4.27.1

I tried running it on latest UE5 early access 2 which causes VRMocap_PlayerPawn_BP.uasset not visible in UE (however it is present on disk) - I read that this has been reported by other people but I haven't found solution to this even though in your video VRMocap_PlayerPawn_BP.uasset is correctly visible and usable in UE5 (just to mention you are using UE5 early access 1 in your video so maybe that is the reason)

I'm considering downgrading to UE 4.26.2 and using latest revision available for this UE version 840a441 (from 17-aug-2021) and see if it works. (hope I won't miss some of the features or bugfixes added in later revisions)

I would just mention that I don't have iphone so I cannot do facial tracking and I'm using older Vive controllers instead of index controllers but they run fine after remapping buttons. and I guess this shouldn't be the reason why it is not working as expected.

thank you for your time and I wish you happy holidays!
