### ISSUE TITLE
Actor can’t follow after successful binding

### ISSUE THREAD

**Issue by sunfeiran0228** [Megasteakman/VRMocap#18]
hi friend, 
when we drag the VRmocap_playerpawn into our level and start play, unfortunately the pink circle and red circle are not movable. After we successfully bind the character by pressing both the triggers of htc vive, the character cannot be controlled by our trackers. Would you help us figure out the problem?

**Comment by sunfeiran0228** [comment]
Unable To Cast to Metahuman Anim BP
MocapActor Hegiht Is 143.393677
BP_Bernice_4.Body f_body
Locator Mode Is Active
Unable To Cast to CC3 Anim BP
BP_Bernice_4.Face Bernice_FaceMesh Mocap Actor Added To Player
BP_Bernice_4.Body f_body Mocap Actor Added To Player

**Comment by Megasteakman** [comment]
Thanks for the additional information.  My initial guess is that the meshes don't have the vr mocap animation blueprints added.  Are you trying to make a hybrid character with a CC3 body and a metahuman head?  Here's the latest information on how to set that up: https://youtu.be/RMyjyF5ea6U?t=74

**Comment by sunfeiran0228** [comment]
Thanks for your help， I've seen the video you sent，but I can't solve the problem.  I can't search for any skeletons in VRMocap/AnimBPs/VRMocap_UE4Mannequin_AnimBP->Retarget Anim Blueprints->Duplicate Anim Blueprints and Retarget->Select Skeleton.
I tried many times，the following error still appears：
Unable To Cast To UE4 Mannequin
MocapActor Height Is 165.563797
Locator Mode Is Active
Unable To Cast to CC3 Anim BP
tt_02_2.SK_Mannequin SK_Mannequin Mocap Actor Added To Player
Would you have a detailed video about ordinary character model binding Tracker?
Thank you so much

**Comment by Megasteakman** [comment]
I think I know what is going on.  Because the VRMocap is casting to a specific animation blueprint, it's probably not finding the retargeted one that you made.

In the Wiki I have this note about importing characters:

NOTE: If you are importing a CC3 character, make sure you use the preexisting iCloneCC3DefaultMale_Skeleton1, in VRMocap/Assets.

I think that this is the best way to import characters (using the existing skeleton on import).  I might look into another way to do this, but I think having less skeletons helps a lot of UE4 workflows.
