### ISSUE TITLE
uasset not showing up in X-UE Version

### ISSUE THREAD

**Issue by Nightfallnotfound** [Megasteakman/VRMocap#19]
Good Day, I have a small Issue regarding the opening and use of your repo. Whenever I follow your youtube tutorial on how to get the assets into Unreal Engine, I fail.
The Files VRMocap_EditorWidget.uasset, etc, which are in the first folder just won't show up, whatever I do. 5.0.0, 4.26, 4.27 none work. I did it the right way over the File Explorer from Windows and it still decides to not show up, on the other hand, some .uasset show up, some don't.

I am really confused about what to do... Thanks for your help

**Comment by Megasteakman** [comment]
I just tested this out on 5.0 and 4.27.  The editor widget does appear in 4.27 in a blank project, but it doesn't work in 5.0.  Maybe it's because I've installed the editor utility plugin, although I do believe this is on a per project basis vs engine level.  If you need it in 5.0, download an earlier commit that doesn't have 4.27 in the title.  Apparently 4.27 is a strange branch that will hopefully be merged into 5.0 on release, but for now most of the things I'm making don't work in 5.0.  Also, choosing an earlier commit will be the 4.26 version, so that should work.  I hope this helps!

**Comment by Nightfallnotfound** [comment]
Thanks for your time and your fast reply. Yeah, looks like it, got it working tho in 4.27 as you mentioned, the other versions just don't wanna. The 4.26 branch didn't do the job so tried it again with 4.27, restarted my pc and everything showed up. Currently watching your youtube tutorial and figuring out, how to get a shot and maybe finally record a scene for my project. This has been a journey. 
Thanks again for the reply, appreciate it
